name: teneo

services:
  db:
    image: postgres:17-alpine
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    command: 
      - -c
      - log_hostname=off
      - -c
      - ssl=on
      - -c
      - ssl_cert_file=/var/lib/postgresql/data/server.crt
      - -c
      - ssl_key_file=/var/lib/postgresql/data/server.key
    init: true
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - db_net
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s
    labels:
      - be.libis.service=teneo
      - be.libis.environment=production
      - be.libis.instance=ingester
      - be.libis.component=db

  db_admin:
    image: dpage/pgadmin4
    networks:
      - db_net
      - app_net
    ports:
      - "7004:5050"
    environment:
      TZ: "Europe/Brussels"
      PGADMIN_DEFAULT_EMAIL: ${DBADMIN_USER:-admin@libis.be}
      PGADMIN_DEFAULT_PASSWORD: ${DBADMIN_PWD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOG_FILE: "'/var/lib/pgadmin/pgadmin4.log'"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: "5050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db_admin_data:/var/lib/pgadmin
      - db_admin_logs:/var/log/pgadmin
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    labels:
      - be.libis.service=teneo
      - be.libis.environment=production
      - be.libis.instance=ingester
      - be.libis.component=db_admin


  db_tool:
    image: ${RUBY_IMAGE}:${RUBY_VERSION}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    working_dir: /app
    command: "irb"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      BUNDLE_COMMAND: install
      GEMS_PATH: /app/vendor/bundle
      BUNDLE_PATH: /app/vendor/bundle
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      DB_ADAPTER: ${DB_ADAPTER}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - db_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./gem:/app
    restart: no
    profiles:
      - db_tool
    labels:
      - be.libis.be.service=teneo
      - be.libis.be.environment=production
      - be.libis.be.instance=ingester
      - be.libis.be.component=db_tool

volumes:
  db_data:
    driver: local
    labels:
      - be.libis.be.service=teneo
      - be.libis.be.environment=production
      - be.libis.be.instance=ingester
      - be.libis.be.component=db

  db_admin_data:
    driver: local
    labels:
      - be.libis.be.service=teneo
      - be.libis.be.environment=production
      - be.libis.be.instance=ingester
      - be.libis.be.component=db_admin

  db_admin_logs:
    driver: local
    labels:
      - be.libis.be.service=teneo
      - be.libis.be.environment=production
      - be.libis.be.instance=ingester
      - be.libis.be.component=db_admin
    
networks:
  app_net:
    driver: bridge
    attachable: true
    labels:
      - be.libis.be.service=teneo
      - be.libis.be.environment=production
      - be.libis.be.instance=ingester
      - be.libis.be.component=app

  db_net:
    driver: bridge
    attachable: true
    labels:
      - be.libis.be.service=teneo
      - be.libis.be.environment=production
      - be.libis.be.instance=ingester
      - be.libis.be.component=network
