name: teneo

services:
  db:
    image: postgres:17-alpine
    init: true
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - db_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s

  db_tool:
    image: ${RUBY_IMAGE}:${RUBY_VERSION}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    working_dir: /app
    command: "irb"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      BUNDLE_COMMAND: install
      GEMS_PATH: /app/vendor/bundle
      BUNDLE_PATH: /app/vendor/bundle
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      DB_ADAPTER: ${DB_ADAPTER}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - db_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/app
    restart: no
    profiles:
      - db_tool
    labels:
      - be.libis.be.service=teneo
      - be.libis.be.environment=production
      - be.libis.be.instance=ingester
      - be.libis.be.component=db_tool

volumes:
  db_data:
    driver: local
    
networks:
  db_net:
    driver: bridge
    attachable: true
