# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in teneo-data_model.gemspec
gemspec

group :development do
  gem 'rubocop', '~> 1.0', '>= 1.74.0'
  gem 'ruby-lsp', '~> 0.0', '>= 0.23.11'
end

gem 'rake', '~> 13.0', '>= 13.2.1'
gem 'rspec', '~> 3.0', '>= 3.13.0'

gem 'awesome_print'
