# frozen_string_literal: true

require 'dotenv'
Dotenv.load('.env.local', '.env')

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec)
rescue LoadError # rubocop:disable Lint/SuppressedException
end

require 'sequel'
require 'logger'

$LOAD_PATH.unshift 'lib'

require 'teneo/data_model'

def db_connect(**opts)
  puts 'Connecting to database ...'
  Teneo::DataModel::Database.instance.config(**opts)
  db = Teneo::DataModel::Database.instance.reconnect
  if ENV['LOGGING']&.downcase == 'debug'
    db.sql_log_level = :debug
    db.loggers << Logger.new($stdout)
  end
  puts 'Connected to database!'
  yield(db) if block_given?
  db
end

namespace :db do
  desc 'Run migrations'
  task :migrate, [:version] do |_t, args|
    puts 'Run migrations'
    puts '=============='
    require 'sequel/core'
    Sequel.extension :migration
    version = args[:version].to_i if args[:version]
    db_connect do |db|
      Sequel::Migrator.run(db, ENV['MIGRATIONS_DIR'], target: version)
    end
  end

  desc 'Run seeds'
  task :seed do
    puts 'Run seeds'
    puts '========='
    require 'sequel/extensions/seed'
    Sequel.extension :seed
    $LOAD_PATH.unshift File.expand_path('lib', __dir__)
    require 'teneo/data_model'
    db_connect do |db|
      Sequel::Seed.setup ENV.fetch('RUBY_ENV', 'development').to_sym
      Sequel::Seeder.apply(db, './db/seeds')
    end
  end
end
