services:
  db:
    image: postgres:16-alpine
    user: "1000:1000"
    hostname: db
    command: ["postgres", "-c", "log_hostname=off"]
    init: true
    shm_size: 128mb
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata

    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teneo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
    