# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'pg', '~> 1.5', '>= 1.5.6'
gem 'puma', '~> 6.4', '>= 6.4.2'
gem 'refrigerator', '~> 1.7'
gem 'roda', '~> 3.81'
gem 'sequel', '~> 5.81'
gem 'sequel_pg', '~> 1.17', '>= 1.17.1'

group :development do
  gem 'rack-unreloader', '~> 2.1'
  gem 'rubocop', '~> 1.64', '>= 1.64.1'
  gem 'ruby-lsp', '~> 0.17.4'
end

gem 'awesome_print'
